class ErrorEnum:
    NONE = 0
    CARD_READ_ERROR = 1
    CONFIG_FILE_MISSING = 2
    FACTORY_RESET_FAILED = 3
    WIFI_CONNECTION_ERROR = 4
    TIME_SYNC_ERROR = 5
    MQTT_PUBLISH_ERROR = 6
    MQTT_CONNECT_ERROR = 7
    UPDATE_CONFIG_ERROR = 8